name: Executar por evento de push e de hora em hora

on:
  push:    # Aciona quando ocorre um push
  schedule:
    - cron: '0 * * * *'   # De hora em hora, no primeiro minuto

jobs:
  build:   # nome do job
    runs-on: ubuntu-latest   #roda em um computador remoto do github
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3   # baixa todos os arquivos do meu repositório para esse ambiente

      - name: Rodar script ou comando   
        run: echo "Executando o workflow"   # retorna no terminal