name: Executar por evento de push e de hora em hora

on:
  # Aciona quando ocorre um push
  push:    
  schedule:
    # Agendando execução do push de hora em hora, no primeiro minuto
    - cron: '0 * * * *'   

jobs:
  build:   
    runs-on: ubuntu-latest   
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3   

      - name: Rodar script ou comando   
        run: echo "Executando o workflow"   